ShahadatApp/Controllers/CitizenController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.IO;
using System.Web;
using System.Web.Mvc;
using ShahadatApp.DAL;
using ShahadatApp.Models;
using PagedList;
using System.Threading.Tasks;

namespace ShahadatApp.Controllers
{
    public class CitizenController : Controller
    {
        private ShahadatAppContext db = new ShahadatAppContext();

        // GET: Citizen
        public ActionResult Index(string searchString, int? page)
        {
            ViewBag.CurrentFilter = searchString;
            var citizen = db.Citizen.Include(c => c.Area);
            

            if(!String.IsNullOrEmpty(searchString))
                citizen = citizen.Where(c => c.Kawmy.Contains(searchString));
            citizen = citizen.OrderBy(c => c.MktbCode);

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(citizen.ToPagedList(pageNumber, pageSize));
            //return View(citizen.ToList());
        }

        // GET: Citizen/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Citizen citizen = db.Citizen.Find(id);
            if (citizen == null)
            {
                return HttpNotFound();
            }
            return View(citizen);
        }

        // GET: Citizen/Create
        public ActionResult Create()
        {
            ViewBag.MktbCode = new SelectList(db.Area, "MktbCode", "Name");
            return View();
        }

        // POST: Citizen/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Kawmy,FullName,Phone,WhatsAppUser,Milad,MktbCode,Mosalsal,IDImage,PersonalPhoto")] Citizen citizen)
        {
            if (ModelState.IsValid)
            {
                db.Citizen.Add(citizen);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MktbCode = new SelectList(db.Area, "MktbCode", "Name", citizen.MktbCode);
            return View(citizen);
        }

        // GET: Citizen/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Citizen citizen = db.Citizen.Find(id);
            if (citizen == null)
            {
                return HttpNotFound();
            }
            ViewBag.MktbCode = new SelectList(db.Area, "MktbCode", "Name", citizen.MktbCode);
            return View(citizen);
        }

        // POST: Citizen/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Kawmy,FullName,Phone,WhatsAppUser,Milad,MktbCode,Mosalsal,IDImage,PersonalPhoto")] Citizen citizen)
        {
            if (ModelState.IsValid)
            {
                db.Entry(citizen).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MktbCode = new SelectList(db.Area, "MktbCode", "Name", citizen.MktbCode);
            return View(citizen);
        }

        // GET: Citizen/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Citizen citizen = db.Citizen.Find(id);
            if (citizen == null)
            {
                return HttpNotFound();
            }
            return View(citizen);
        }

        // POST: Citizen/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Citizen citizen = db.Citizen.Find(id);
            var Talabat = db.Talab.Where(t => t.Kawmy == citizen.Kawmy);
            if(Talabat != null)
                foreach (Talab talab in Talabat)
                    db.Talab.Remove(talab);

            db.Citizen.Remove(citizen);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult MorfkatNotSent(bool isCopy=false)
        {
            var talabat = db.Talab.Include(c => c.Citizen).Where(t => t.Citizen.MorfkatRecieved == true && t.Citizen.MorfkatSent == false && t.ServiceType.Contains("كارنيه"));

            List<Citizen> Citizens = new List<Citizen>();
            foreach (var t in talabat)
            {
                Citizens.Add(t.Citizen);
            }
            Citizens = Citizens.Distinct().ToList();

            if(isCopy)
            {
                string sourceFile = @"D:\morfat\";
                string destinationFile = @"F:\M\";
                foreach (var item in Citizens)
                {
                    try
                    {


                        System.IO.File.Copy(sourceFile + item.Kawmy + ".jpg", destinationFile + item.Kawmy + ".jpg", true);
                        System.IO.File.Copy(sourceFile + item.Kawmy + "_1.jpg", destinationFile + item.Kawmy + "_1.jpg", true);


                    }
                    catch (IOException iox)
                    {
                        //return Json(iox.Message, JsonRequestBehavior.AllowGet);
                    }
                }
                return Json("تم النسخ بنجاح", JsonRequestBehavior.AllowGet);
            }
            //CopyMorfkat(Citizens.Select(c => c.Kawmy).ToList());

            return View(Citizens.ToList());
        }
        public ActionResult CopyMorfkat(List<string> Kawmys)
        {
            string sourceFile = @"D:\morfat\";
            string destinationFile = @"F:\M\";
            try
            {
                foreach (var item in Kawmys)
                {

                    System.IO.File.Copy(sourceFile + item + ".jpg", destinationFile + item + ".jpg", true);
                    System.IO.File.Copy(sourceFile + item + "_1.jpg", destinationFile + item + "_1.jpg", true);

                }
            }
            catch (IOException)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            return Json(true, JsonRequestBehavior.AllowGet);
        }

    }
}

ShahadatApp/Controllers/TalabController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ShahadatApp.DAL;
using ShahadatApp.Models;
using PagedList;
using WhatsAppApi;
using ShahadatApp.Hubs;
using System.Web.Script.Serialization;
namespace ShahadatApp.Controllers
{
    public class TalabController : Controller
    {
        private ShahadatAppContext db = new ShahadatAppContext();
        private ShahadatAppContext _db = new ShahadatAppContext();

        //List<string> servicePostion = new List<string>()
        //    {
        //        "", "إستخراج كاشير", "تسجيل بيانات", "مراجعة بيانات", "طباعة الخدمة", "إستلام مندوب", "الخدمة جاهزة للأستلام", "تم تسليم الخدمة"
        //    };
        List<string> servicePostion = new List<string>()
            {
                "",  "طباعة الخدمة","الخدمة جاهزة للأستلام", "تم تسليم الخدمة"
            };
        List<string> Intervals = new List<string>() { "", "اقل من ساعة", "من ساعة إلى 3", "من 3 إلى 6 ساعات", "من 6 إلى 12 ساعة", "من 12 إلى 24 ساعة" };
        List<string> TalabStatus = new List<string>() { "تم ابلاغه بالدفع", "تم ابلاغه فورى", "تم الدفع", "تفاوض","الغاء الطلب" };
        List<string> CertificateType = new List<string>() { "", "مزدوج الجنسية" };


        // GET: Talab
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, string selectOption, int? page, DateTime? fromDate , DateTime? toDate,string talabStatus)
        {

            return HttpNotFound();
            
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentFilter = searchString;
            ViewBag.FromDate = DateTime.Now;
            ViewBag.ToDate = DateTime.Now;
            var OptionList = new List<string>() { "", "طباعة الخدمة", "الخدمة جاهزة للأستلام" };

            //var TalabStatus = new List<string>() { "", "تم ابلاغه بالدفع", "تم ابلاغه بالدفع 2", "تم الدفع" };
            ViewBag.TalabStatus = new SelectList(TalabStatus);
            ViewBag.SelectOption = new SelectList(OptionList);

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            var talab = db.Talab.Include(t => t.Area).Include(t => t.Citizen).Include(t => t.PrintArea);


            if (!String.IsNullOrEmpty(selectOption))
            {
                talab = talab.Where(t => t.ServicePostion.Contains(selectOption));
            }
            if (!String.IsNullOrEmpty(searchString))
            {
                talab = talab.Where(t => t.TalabNum.Contains(searchString) || t.Kawmy.Contains(searchString) || t.Citizen.FullName.Contains(searchString));
            }
            if(fromDate != null && toDate != null)
            {
                talab = talab.Where(t => t.CreateDate >= fromDate && t.CreateDate <= toDate);
            }
            if (!String.IsNullOrEmpty(talabStatus))
            {
                talab = talab.Where(t => t.TalabStatus.Contains(talabStatus));
            }

            talab = talab.OrderByDescending(t => t.CreateDate);
            //int pageSize = 10;
            //int pageNumber = (page ?? 1);

            return View(talab.ToList());
        }

        // GET: Talab/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Talab talab = db.Talab.Find(id);
            if (talab == null)
            {
                return HttpNotFound();
            }
            return View(talab);
        }

        List<Area> SortPrintArea(List<Area> listOfPrintArea)
        {
            List<Area> SortedArea = new List<Area>();
            SortedArea.Add(listOfPrintArea.Where(a => a.Name.Contains("إدارة")).SingleOrDefault());
            SortedArea.Add(listOfPrintArea.Where(a => a.Name.Contains("منطقة تجنيد وتعبئة القاهرة")).SingleOrDefault());
            SortedArea.Add(listOfPrintArea.Where(a => a.Name.Contains("منطقة تجنيد وتعبئة الإسكندرية")).SingleOrDefault());
            SortedArea.Add(listOfPrintArea.Where(a => a.Name.Contains("منطقة تجنيد وتعبئة المنصورة")).SingleOrDefault());
            SortedArea.Add(listOfPrintArea.Where(a => a.Name.Contains("منطقة تجنيد وتعبئة أسيوط")).SingleOrDefault());
            SortedArea.Add(listOfPrintArea.Where(a => a.Name.Contains("منطقة تجنيد وتعبئة الجيزة")).SingleOrDefault());
            SortedArea.Add(listOfPrintArea.Where(a => a.Name.Contains("منطقة تجنيد وتعبئة طنطا")).SingleOrDefault());
            SortedArea.Add(listOfPrintArea.Where(a => a.Name.Contains("منطقة تجنيد وتعبئة المنيا")).SingleOrDefault());
            SortedArea.Add(listOfPrintArea.Where(a => a.Name.Contains("منطقة تجنيد وتعبئة الزقازيق")).SingleOrDefault());
            SortedArea.Add(listOfPrintArea.Where(a => a.Name.Contains("منطقة تجنيد وتعبئة قنا")).SingleOrDefault());

            return SortedArea;
        }

        List<Area> SortRecievedArea(List<Area> listOfRecievedArea)
        {
            List<Area> SortedArea = new List<Area>();
            SortedArea.Add(listOfRecievedArea.Where(a => a.Name.Contains("إدارة")).SingleOrDefault());
            SortedArea.AddRange(listOfRecievedArea.Where(a => a.Qesm.Contains("القاهرة") && !a.Name.Contains("إدارة")));
            SortedArea.AddRange(listOfRecievedArea.Where(a => a.Qesm.Contains("القليوبية")));
            SortedArea.AddRange(listOfRecievedArea.Where(a => a.Qesm.Contains("حلوان")));
            SortedArea.AddRange(listOfRecievedArea.Where(a => a.Qesm.Contains("الاسكندرية")));
            SortedArea.AddRange(listOfRecievedArea.Where(a => a.Qesm.Contains("المنصورة")));
            SortedArea.AddRange(listOfRecievedArea.Where(a => a.Qesm.Contains("أسيوط")));
            SortedArea.AddRange(listOfRecievedArea.Where(a => a.Qesm.Contains("الجيزة")));
            SortedArea.AddRange(listOfRecievedArea.Where(a => a.Qesm.Contains("طنطا")));
            SortedArea.AddRange(listOfRecievedArea.Where(a => a.Qesm.Contains("المنيا")));
            SortedArea.AddRange(listOfRecievedArea.Where(a => a.Qesm.Contains("الزقازيق")));
            SortedArea.AddRange(listOfRecievedArea.Where(a => a.Qesm.Contains("قنا")));
            return SortedArea;
        }

        // GET: Talab/Create
        public ActionResult Create()
        {
            List<Area> PrintArea = db.Area.Where(area => area.Name.Contains("منطقة") || area.Name.Contains("إدارة")).ToList();


            List<Area> SortedArea = SortPrintArea(PrintArea);

            var ReceivedArea = (from area in db.Area
                               where area.Name.Contains("إدارة") || area.Name.Contains("منطقة") || area.Name.Contains("قسم تجنيد")
                               || area.MktbCode == "237" || area.MktbCode == "152" || area.MktbCode == "78" || area.MktbCode == "236" || area.MktbCode == "251" || area.MktbCode == "262" || area.MktbCode == "221" || area.MktbCode == "163" || area.MktbCode == "44" || area.MktbCode == "401"
                               select area).ToList();
            //var ReceivedArea = (from area in db.Area
            //                   select area).ToList();

            List<Area> NewReceivedArea = SortRecievedArea(ReceivedArea);
            ViewBag.TalabStatus = new SelectList(TalabStatus);
            ViewBag.CertificateType = new SelectList(CertificateType);
            ViewBag.ServicePostion = new SelectList(servicePostion,"", new List<string> { "تم تسليم الخدمة", "الخدمة جاهزة للأستلام" });
            ViewBag.CardServicePostion = new SelectList(servicePostion,"", new List<string> { "تم تسليم الخدمة", "الخدمة جاهزة للأستلام" });
            ViewBag.ServiceType = new SelectList(new List<string>() { "","شهادة", "كارنيه", "شهادة و كارنيه" });
            ViewBag.RecievedAreaID = new SelectList(NewReceivedArea, "MktbCode", "Name");
            ViewBag.Kawmy = new SelectList(db.Citizen, "Kawmy", "FullName");
            ViewBag.PrintAreaID = new SelectList(SortedArea, "MktbCode", "Name");
            return View();
        }

        // POST: Talab/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TalabNum,Kawmy,TalabStatus,PrintAreaID,RecievedAreaID,ServicePostion,CardServicePostion,ServiceType,PrintDate,CardPrintDate,Notes,CertificateType,Citizen")] Talab talab)
        {
           
            talab.CreateDate = DateTime.Now;
            talab.Kawmy = talab.Citizen.Kawmy;

            if (ModelState.IsValid)
            {
                talab.Citizen.Phone = talab.Citizen.Phone.StartsWith("01") ? "+2" + talab.Citizen.Phone : talab.Citizen.Phone;
                var citizen = db.Citizen.Find(talab.Citizen.Kawmy);

                if (citizen != null)
                    talab.Citizen = null;

                db.Talab.Add(talab);
                db.SaveChanges();
                return RedirectToAction("TalabatByArea");
            }
            ViewBag.TalabStatus = new SelectList(new List<string>() { "تم ابلاغه بالدفع", "تم الدفع" });
            ViewBag.ServicePostion = new SelectList(servicePostion,"", new List<string> { "تم تسليم الخدمة", "الخدمة جاهزة للأستلام" });
            
            ViewBag.ServiceType = new SelectList(new List<string>() { "شهادة", "كارنيه", "شهادة و كارنيه" });
            ViewBag.CardServicePostion = new SelectList(servicePostion, "", new List<string> { "تم تسليم الخدمة", "الخدمة جاهزة للأستلام" });
            
            ViewBag.Kawmy = new SelectList(db.Citizen, "Kawmy", "FullName", talab.Kawmy);
            
            return Redirect("Create");
            
        }

        // GET: Talab/Edit/5
        public ActionResult Edit(string id)

ShahadatApp/Views/Shared/TalabError.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Error</title>
</head>
<body>
    <hgroup>
        <h1>إضافة</h1>
        <h2>هذا الطلب مُضاف من قبل</h2>
    </hgroup>
</body>
</html>

ShahadatApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - E.Center For Recruitment Services</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/Scripts/jquery.signalR-2.4.3.min.js")
    @Scripts.Render("~/signalr/Hubs/")
    <script src="~/Scripts/sweetalert.min.js"></script>
    @*<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>*@
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    
    <script type="text/javascript" src="https://unpkg.com/xlsx@0.15.1/dist/xlsx.full.min.js"></script>
    <script src="~/Scripts/JsBarcode.all.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <style>
        /*body {
            background-image: url('../../Icons/wp2633863.png');
        }*/
        .material-symbols-outlined {
            font-size:2vw;
            display:inline;
        }
        li{
            font-size:1.3vw;
        }
        /*.dropdown:hover .dropdown-content {display: block;}*/
        .dark-mode {
            background-color: #1d2a35;
            color: white;
        }

        .light-mode {
            background-color: white;
            color: black;
        }


        .change {
            cursor: pointer;
            border: 1px solid #555;
            border-radius: 40%;
            width: 20px;
            text-align: center;
            padding: 5px;
            margin-left: 8px;
            background-color: white;
            color: black;
        }

        .dark {
            background-color: #222;
            color: #e6e6e6;
        }

        .switch {
            position: relative;
            display: inline-block;
            width: 46px;
            height: 20px;
            top: 25%;
        }

            .switch input {
                opacity: 0;
                width: 0;
                height: 0;
            }

        .slider {
            position: absolute;
            cursor: pointer;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-color: #ccc;
            -webkit-transition: .4s;
            transition: .4s;
        }

            .slider:before {
                position: absolute;
                content: "";
                height: 16px;
                width: 16px;
                left: 2px;
                bottom: 2px;
                background-color: white;
                -webkit-transition: .4s;
                transition: .4s;
            }

        input:checked + .slider {
            background-color: #2196F3;
        }

        input:focus + .slider {
            box-shadow: 0 0 1px #2196F3;
        }

        input:checked + .slider:before {
            -webkit-transform: translateX(23px);
            -ms-transform: translateX(23px);
            transform: translateX(26px);
        }

        /* Rounded sliders */
        .slider.round {
            border-radius: 34px;
        }

            .slider.round:before {
                border-radius: 50%;
            }

        #logo {
            width: 60px;
            height: 60px;
            transition: width 2s, height 2s;
        }

            #logo:hover {
                width: 100px;
                height: 100px;
            }
    </style>
</head>
<body style="direction:rtl" id="bodyId">
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a href="@Url.Action("Index", "Home")">
                    <img src="~/Icons/favicon.png" alt="Home Page" style="width:42px;height:42px;">
                </a>
            </div>

            <div class="collapse navbar-collapse" id="collapsibleNavbar">

                <ul class="navbar-nav">
                    <li>
                        <a class="nav-link" href="@Url.Action("TalabatByArea", "Talab")">طلبات<i class="bi bi-cart"></i></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">السحبات</a>
                        <ul class="dropdown-menu">
                            @* <li>Html.ActionLink("طلبات", "TalabatByArea", "Talab", null, new { @class = "dropdown-item", style = "text-decoration:none;" })</li>*@
                            <li>
                                @*<li>@Html.ActionLink("تم ابلاغه الدفع", "TmEbla8", "Talab", null, new { @class = "dropdown-item", style = "text-decoration:none;" })</li>*@
                            <li class="dropdown-item">@Html.ActionLink("كشوفات المناطق", "AreaReports", "Talab", null, new {@class= "dropdown-item", style = "text-decoration:none; display:inline;" })<span class="material-symbols-outlined" style="display:inline">summarize</span></li>
                            <li class="dropdown-item">@Html.ActionLink("مرفقات الطلبات", "Morfkat", "Talab", null, new { @class = "dropdown-item", style = "text-decoration:none; display:inline;" }) <span class="material-symbols-outlined">image</span></li>
                            <li class="dropdown-item">@Html.ActionLink("تسليم الخدمات", "ServiceReady", "Talab", null, new {@class= "dropdown-item", style = "text-decoration:none; display:inline;" }) <span class="material-symbols-outlined">approval_delegation</span></li>
                            <li class="dropdown-item">@Html.ActionLink("طلبات ليس لها موقف", "PaidWithoutPosition", "Talab", null, new { @class = "dropdown-item", style = "text-decoration:none; display:inline;" })</li>
                            <li class="dropdown-item">@Html.ActionLink("مرفقات لم يتم سحبها", "MorfkatNotSent", "Citizen", null, new { @class = "dropdown-item", style = "text-decoration:none; display:inline;" })</li>
                        </ul>
                    </li>
                    <li>
                        <a class="nav-link" onclick="window.open('https://192.168.1.17:3000')">
                            استلام المرفقات
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="@Url.Action("OrdersReport", "Talab")">
                            تقارير الطلبات
                            <span class="material-symbols-outlined" style="font-size:1.5vw">
                                query_stats
                            </span>
                        </a>
                    </li>
                </ul>

            </div>
            <div>
                <button class="btn" type="button" onclick="location.href='@Url.Action("Index", "Notification")'">
                    <span class="material-symbols-outlined" style="float:left; color:white;">notifications</span>
                    <span class="badge rounded-pill bg-danger" id="ntCnt"></span>
                </button>
            </div>
            <span class="material-symbols-outlined" style="color:white; float:left">dark_mode</span>
            <label class="notification-icon switch" style="float:left">

                <input type="checkbox" onclick="changeStatus()" id="check">
                @*<span class="round material-symbols-rounded">dark_mode</span>*@
                @*<span class="round material-symbols-rounded">light_mode</span>*@
                <span class="slider round"> </span>
            </label>
        </div>
    </nav>

    <div class="container body-content">
        <br />
        
        @RenderBody()
        <br />
        <script src="~/Scripts/DarkScript.js"></script>

    </div>
    <footer class="fixed-bottom text-center text-bg-dark">
        <p>&copy; @DateTime.Now.Year - E Center For Recruitment Service</p>
    </footer>
    @RenderSection("scripts", required: false)
</body>
</html>

<script>
    $("body").on("click", ".mybuttonclass", function (e) {

        var myBtn = $(e.currentTarget);
        var itemId = myBtn.attr("data-id");
        var innerSpan = $(myBtn.get(0).firstElementChild);
        e.preventDefault();

        swal({
            //title: "Are you sure?",
            text: "هل تريد ارسال رسالة إلى" + itemId,
            icon: "warning",
            buttons: true,
            dangerMode: true
        }).then(function (value) {

            if (value === true) {
                myBtn.addClass("disabled");
                innerSpan.addClass("fa-spin");
                debugger
                $.ajax({

                    url: '@Url.Action("TalabatByArea", "Talab")',
                    data: { "id": itemId },
                    dataType: "json",
                    success: function (result) {
                        if (result.success === true) {
                            swal({
                                title: "Done!",
                                text: result.message,
                                icon: "success"
                            });
                        } else {
                            swal({
                                title: "Error!",
                                text: result.message,
                                icon: "error"
                            });
                        }

                        myBtn.removeClass("disabled");
                        innerSpan.removeClass("fa-spin");
                    },
                    error: function (xhr, textStatus, error) {
                        swal({
                            title: "Error!",
                            text: xhr.statusText,
                            icon: textStatus
                        });

                        myBtn.removeClass("disabled");
                        innerSpan.removeClass("fa-spin");
                    },
                });
            }
        });
    });

    $(function () {
        // Reference the auto-generated proxy for the hub.

        //var progress = $.connection.myHub;
        var hub = $.connection.myHub;


        // Declare a function on the hub hub so the server can invoke it
        hub.client.displayStatus = function () {
            getData();
            toastr.options = {
                positionClass: "toast-bottom-right",
                timeOut: 3000
            };
            toastr.warning(message);
        };

        // Start the connection
        $.connection.hub.start();
        getData();



        function getData() {
            var divNotificaion = $('#divNotificaion');
            $.ajax({
                url: '/Notification/GetNotification',
                type: 'GET',
                datatype: 'json',
                success: function (data) {
                    
                    data = $.parseJSON(data);
                    if (data.length > 0) {
                        divNotificaion.empty();
                        //// set Count
                        $('#ntCnt').text(data.length);


                        ///Make notification html
                        for (var i = 0; i < data.length; i++) {
                            //var Url = "'location.href="@@Url.Action("DeleteNotification", "Notification", new { id ="+ data[i].NotificationID+"})'";

                            var notification = '<div class="alert alert-success alert-dismissable fade show">' +
                                '<button type="button" class="btn-close closeBtnclass" data-id="' + data[i].NotificationID + '" data-bs-dismiss="alert"></button>'
                        + data[i].Message +
                    '</div>'
                            divNotificaion.append(notification);
                        }

                    }
                }, error: function (r, e, w) {
                }
            });
        }
        
        // Create a function that the hub can call back to display messages.
        hub.client.DisplayNotification = function (message) {

            toastr.options = {
                positionClass: "toast-bottom-right",
                timeOut: 3000
            };
            toastr.warning(message);
        };

        //$.connection.hub.start()
    });
</script>